# Generated by Django 2.2.7 on 2020-03-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diseasename', models.CharField(max_length=2225)),
                ('Remedies', models.CharField(max_length=2225)),
            ],
        ),
    ]
