# Generated by Django 2.2.7 on 2020-03-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remedies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remedies',
            new_name='Remedy',
        ),
    ]
